# version 1.00 date 20/02/2016 auteur(s) Michel Cressant

# Compilation
all: pvd

pvd:
	make -C PVD

# Archivage
archive: archivepvd 

archivepvd:
	make -C PVD archive

# Nettoyage
clean: cleanpvd 

cleanpvd:
	make -C PVD clean
