imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

parameters:
    locale: fr

framework:
    #esi:             ~
    translator: { fallback: fr }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            geography: 'Jsor\Doctrine\PostGIS\Types\GeographyType'
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            numeric_functions:
                stdwithin:    CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STDWithin

# Swiftmailer Configuration
swiftmailer:
    default_mailer: dev_mailer
    mailers:
        dev_mailer:
            transport: "%mailer_transport%"
            host:      "%mailer_host%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            encryption: "%mailer_encryption%"
            port: "%mailer_port%"
            spool:     { type: memory }
        mailer_maternelle:
            transport: "%mailer_plaideurs_transport%"
            host:      "%mailer_plaideurs_host%"
            username:  "%mailer_maternelle_user%"
            password:  "%mailer_maternelle_password%"
            encryption: "%mailer_plaideurs_encryption%"
            port: "%mailer_plaideurs_port%"
            spool:     { type: memory }
        mailer_elementaire:
            transport: "%mailer_plaideurs_transport%"
            host:      "%mailer_plaideurs_host%"
            username:  "%mailer_elementaire_user%"
            password:  "%mailer_elementaire_password%"
            encryption: "%mailer_plaideurs_encryption%"
            port: "%mailer_plaideurs_port%"
            spool:     { type: memory }
        mailer_college:
            transport: "%mailer_plaideurs_transport%"
            host:      "%mailer_plaideurs_host%"
            username:  "%mailer_college_user%"
            password:  "%mailer_college_password%"
            encryption: "%mailer_plaideurs_encryption%"
            port: "%mailer_plaideurs_port%"
            spool:     { type: memory }
        mailer_lycee:
            transport: "%mailer_plaideurs_transport%"
            host:      "%mailer_plaideurs_host%"
            username:  "%mailer_lycee_user%"
            password:  "%mailer_lycee_password%"
            encryption: "%mailer_plaideurs_encryption%"
            port: "%mailer_plaideurs_port%"
            spool:     { type: memory }
        mailer_superieur:
            transport: "%mailer_plaideurs_transport%"
            host:      "%mailer_plaideurs_host%"
            username:  "%mailer_superieur_user%"
            password:  "%mailer_superieur_password%"
            encryption: "%mailer_plaideurs_encryption%"
            port: "%mailer_plaideurs_port%"
            spool:     { type: memory }

fos_user:
    db_driver:     orm
    firewall_name: main
    use_listener: false
    user_class:   Unipik\UserBundle\Entity\Benevole
    service:
            mailer: fos_user.mailer.twig_swift
    registration:
            form:
                    type: Unipik\UserBundle\Form\RegistrationType
            confirmation:
                    enabled: true
                    template:   MailBundle::email.txt.twig
                    from_email:
                         address:        unipik.dev@gmail.com
                         sender_name:    unipik.dev@gmail.com
    profile:
            form:
                    type: Unipik\UserBundle\Form\ProfileFormType

gregwar_captcha: ~
