architecture:
    resource: "@ArchitectureBundle/Resources/config/routing.yml"
    prefix:   /

mail:
    resource: "@MailBundle/Resources/config/routing.yml"
    prefix:   /

intervention:
    resource: "@InterventionBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /


admin_architecture:
    resource: "@ArchitectureBundle/Resources/config/routingAdmin.yml"
    prefix:   /admin/


admin_intervention:
    resource: "@InterventionBundle/Resources/config/routingAdmin.yml"
    prefix:   /admin/

admin_user:
    resource: "@UserBundle/Resources/config/routingAdmin.yml"
    prefix:   /admin/
