# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    userbundle.profile.form.type:
        class: Unipik\UserBundle\Form\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
           - { name: form.type, alias: user_profile }
    mailer_maternelle:
                class:        Unipik\MailBundle\Service\SecondMail
                arguments:    ['@swiftmailer.mailer.mailer_maternelle']
    mailer_elementaire:
                class:        Unipik\MailBundle\Service\SecondMail
                arguments:    ['@swiftmailer.mailer.mailer_elementaire']
    mailer_college:
                class:        Unipik\MailBundle\Service\SecondMail
                arguments:    ['@swiftmailer.mailer.mailer_college']
    mailer_lycee:
                class:        Unipik\MailBundle\Service\SecondMail
                arguments:    ['@swiftmailer.mailer.mailer_lycee']
    mailer_superieur:
                class:        Unipik\MailBundle\Service\SecondMail
                arguments:    ['@swiftmailer.mailer.mailer_superieur']

