# version 1.00 date 13/05/2016 auteur(s) Michel Cressant, Julie Pain
Unipik\UserBundle\Entity\Comite:
    type: entity
    table: comite
    indexes:
        IDX_DC01CA9F98260155:
            columns:
                - region_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nomDepartement:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
            column: nom_departement
    manyToOne:
        region:
            targetEntity: Region
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                region_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        niveauTheme:
            targetEntity: NiveauTheme
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: comite
            joinTable:
                name: comite_niveau_theme
                joinColumns:
                    -
                        name: comite
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: niveau_theme
                        referencedColumnName: id
            orderBy: null
        benevole:
            targetEntity: Benevole
            cascade: {  }
            fetch: LAZY
            mappedBy: comite
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
