Unipik\UserBundle\Entity\Participe:
  type: entity
  id:
    contact:
      associationKey: true
    projet:
      associationKey: true
  fields:
    estTuteur:
      type: boolean
  manyToOne:
    projet:
      targetEntity: Projet
    contact:
          targetEntity: Contact
          inversedBy: participe
