# version 1.00 date 19/10/2016 auteur(s) Pierre Porche

# Compilation
all: sp

sp:
	make -C SP


# Archivage
archive: archivesp

archivesp:
	make -C SP archive



# Nettoyage
clean: cleansp

cleansp:
	make -C SP clean

