# version 1.00 date 13/05/2016 auteur(s) Michel Cressant, Julie Pain
Unipik\InterventionBundle\Entity\Etablissement:
    type: entity
    table: etablissement
    indexes:
        IDX_20FD592C4DE7DC5C:
            columns:
                - adresse_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        uai:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        nom:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        telFixe:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: tel_fixe
        emails:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
        typeEnseignement:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
            column: type_enseignement
        typeCentre:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
            column: type_centre
        typeAutreEtablissement:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
            column: type_autre_etablissement
    manyToOne:
        adresse:
            targetEntity: Adresse
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                adresse_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        contact:
            targetEntity: Contact
            cascade: {  }
            fetch: LAZY
            mappedBy: etablissement
            inversedBy: null
            joinTable: null
            orderBy: null

    lifecycleCallbacks: {  }
