# version 1.00 date 13/05/2016 auteur(s) Michel Cressant, Julie Pain
Unipik\InterventionBundle\Entity\Intervention:
    type: entity
    repositoryClass: Unipik\InterventionBundle\Entity\InterventionRepository
    table: intervention
    indexes:
        IDX_D11814ABE004B434:
            columns:
                - niveau_theme_id
        IDX_D11814ABFF631228:
            columns:
                - etablissement_id
        IDX_D11814ABD61C3573:
            columns:
                - comite_id
        IDX_D11814ABE77B7C09:
            columns:
                - benevole_id
        IDX_D11814AB80E95E18:
            columns:
                - demande_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        dateIntervention:
            type: date
            nullable: true
        lieu:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        nbPersonne:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: nb_personne
        remarques:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
        heure:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        realisee:
            type: boolean
            nullable: false
            length: null
            options:
                fixed: false
        materielDispoPlaidoyer:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
            column: materiel_dispo_plaidoyer
        niveauFrimousse:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: niveau_frimousse
        materiauxFrimousse:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
            column: materiaux_frimousse
        description:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
    manyToOne:
        niveauTheme:
            targetEntity: Unipik\ArchitectureBundle\Entity\NiveauTheme
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                niveau_theme_id:
                    referencedColumnName: id
            orphanRemoval: false
        etablissement:
            targetEntity: Etablissement
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                etablissement_id:
                    referencedColumnName: id
            orphanRemoval: false
        comite:
            targetEntity: Unipik\UserBundle\Entity\Comite
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                comite_id:
                    referencedColumnName: id
            orphanRemoval: false
        benevole:
            targetEntity: Unipik\UserBundle\Entity\Benevole
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                benevole_id:
                    referencedColumnName: id
            orphanRemoval: false
        demande:
            targetEntity: Demande
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                demande_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
