<?php

namespace Unipik\ArchitectureBundle\Repository;

/**
 * NameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NameRepository extends \Doctrine\ORM\EntityRepository
{
}
