# version 1.00, date 20/02/16, auteur Michel Cressant
# Compilation
all: rfd

rfd:
	make -C RFD

# Archivage
archive: archiverfd 

archiverfd:
	make -C RFD archive

# Nettoyage
clean: cleanrfd 

cleanrfd:
	make -C RFD clean
