mail_send_form:
    path: /mail/{name}
    defaults:
        _controller: MailBundle:Mail:sendForm

etablissements_mailing:
    path: /mailing/etablissements
    defaults:
        _controller: MailBundle:Mail:mailingEtablissement

historique_mailing:
    path: /mailing/historique
    defaults:
        _controller: MailBundle:Mail:mailingHistorique