services:
#    mail.example:
#        class: Unipik\MailBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    app.form.mail.recherche:
        class: Unipik\MailBundle\Form\RechercheAvanceeType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }