# version 1.00, date 04/03/16, auteur Pierre Porche
# Compilation
all: Revues

Revues:
	make -C revues


# Archivage
archive: archiverevues

archiverevues:
	make -C revues archive



# Nettoyage
clean: cleanrevues

cleanrevues:
	make -C revues clean

