# version 1.00 date 04/03/2016 auteur(s) Pierre Porche

# Compilation
all: Revues

Revues:
	make -C revues


# Archivage
archive: archiverevues

archiverevues:
	make -C revues archive



# Nettoyage
clean: cleanrevues

cleanrevues:
	make -C revues clean

