# version 1.00, date 20/02/16, auteur Michel Cressant
# Compilation
all: fc
 
fc:
	make -C FC

# Archivage
archive: archivefc 

archivefc:
	make -C FC archive



# Nettoyage
clean : cleanfc 

cleanfc:
	make -C FC clean


