intervention_admin_add:
    path:     /intervention/ajouter
    defaults: { _controller: InterventionBundle:Intervention:ajouter }

etablissement_admin_add:
    path:     /etablissement/ajouter
    defaults: { _controller: InterventionBundle:Etablissement:add }

