intervention_admin_add:
    path:     /intervention/ajouter
    defaults: { _controller: InterventionBundle:Intervention:add }

etablissement_admin_add:
    path:     /etablissement/ajouter
    defaults: { _controller: InterventionBundle:Etablissement:add }

intervention_admin_delete:
    path:   /intervention/supprimer/{id}
    defaults: { _controller: InterventionBundle:Intervention:supprimer }
    requirements:
        id: \d+

etablissement_admin_delete:
    path:   /etablissement/supprimer/{id}
    defaults: { _controller: InterventionBundle:Etablissement:deleteEtablissement }
    requirements:
        id: \d+

intervention_admin_deletes:
    path:   /intervention/supprimer
    defaults: { _controller: InterventionBundle:Intervention:deleteInterventions }

intervention_admin_edit:
    path: /intervention/edit/{id}
    defaults: {_controller: InterventionBundle:Intervention:edit}
    requirements:
        id: \d+

etablissement_admin_deletes:
    path:   /etablissement/supprimer
    defaults: { _controller: InterventionBundle:Etablissement:deleteEtablissements }

etablissement_admin_edit:
    path:   /etablissement/edit/{id}
    defaults: { _controller: InterventionBundle:Etablissement:edit }