intervention_view:
    path: /{id}/
    defaults: {_controller: InterventionBundle:Intervention:consultation}


intervention_request:
    path:     /demande/{id}/
    defaults:
        _controller: InterventionBundle:Intervention:demande

intervention_list:
    path:   /plaidoyer/
    defaults:
        _controller: InterventionBundle:Intervention:listPlaidoyers
