# version 1.00 date 13/05/2016 auteur(s) Michel Cressant, Julie Pain

# Route intervention
intervention:
    resource: "@InterventionBundle/Resources/config/routingIntervention.yml"

# Route etablissement
etablissement:
    resource: "@InterventionBundle/Resources/config/routingEtablissement.yml"

# Route Vente
ventes:
    resource: "@InterventionBundle/Resources/config/routingVentes.yml"

