stats_nombre_interventions:
    path : /interventions
    defaults:
        _controller: InterventionBundle:Stats:interventions

stats_ventes:
    path: /ventes
    defaults:
        _controller: InterventionBundle:Stats:ventes