intervention_request:
    path:     /demande/{id}
    defaults:
        _controller: InterventionBundle:Intervention:demande

intervention_list:
    path:   /plaidoyer
    defaults:
        _controller: InterventionBundle:Intervention:listPlaidoyers

intervention_view:
    path: /{id}
    defaults: {_controller: InterventionBundle:Intervention:consultation}

etablissement_list:
    path:   /etablissement
    defaults:
        _controller: InterventionBundle:Intervention:listEtablissement
