# version 1.00 date 13/05/2016 auteur(s) Michel Cressant, Julie Pain
intervention_request:
    path:     /intervention/demande
    defaults:
        _controller: InterventionBundle:Intervention:demande

intervention_list:
    path:   /intervention
    defaults:
        _controller: InterventionBundle:Intervention:liste

intervention_attributed:
    path: /intervention/attribuees
    defaults: {_controller: InterventionBundle:Intervention:attribuees}

intervention_view:
    path: /intervention/{id}
    defaults: {_controller: InterventionBundle:Intervention:consultation}
    requirements:
        id: \d+

intervention_edit:
    path: /intervention/edit/{id}
    defaults: {_controller: InterventionBundle:Intervention:edit}
    requirements:
        id: \d+

intervention_self_attribute:
    path: /intervention/attribution
    defaults: {_controller: InterventionBundle:Intervention:attribution}

intervention_self_desattribute:
    path: /intervention/desattribution
    defaults: {_controller: InterventionBundle:Intervention:desattribution}

intervention_cancel:
    path: /intervention/annuler/{id}
    defaults: {_controller: InterventionBundle:Intervention:annuler}

etablissement_list:
    path:   /etablissement
    defaults:
        _controller: InterventionBundle:Etablissement:liste

etablissement_view:
    path:   /etablissement/{id}
    defaults:
        _controller: InterventionBundle:Etablissement:consultation
    requirements:
        id: \d+

interventions_benevole:
    path: /intervention/toast
    defaults: {_controller: InterventionBundle:Intervention:toast}