intervention_request:
    path:     /intervention/demande/{id}
    defaults:
        _controller: InterventionBundle:Intervention:demande

intervention_list:
    path:   /intervention/plaidoyer
    defaults:
        _controller: InterventionBundle:Intervention:listePlaidoyers

intervention_view:
    path: /intervention/{id}
    defaults: {_controller: InterventionBundle:Intervention:consultation}



etablissement_list:
    path:   /etablissement
    defaults:
        _controller: InterventionBundle:Etablissement:liste

etablissement_view:
    path:   /etablissement/{id}
    defaults:
        _controller: InterventionBundle:Etablissement:consultation
