intervention_admin_add:
    path:     /intervention/ajouter
    defaults: { _controller: InterventionBundle:Intervention:ajouter }

etablissement_admin_add:
    path:     /etablissement/ajouter
    defaults: { _controller: InterventionBundle:Etablissement:add }

intervention_admin_delete:
    path:   /intervention/supprimer/{id}
    defaults: { _controller: InterventionBundle:Intervention:supprimer }
    requirements:
        id: \d+

