# version 1.00 date 13/05/2016 auteur(s) Michel Cressant, Julie Pain

# Route intervention
intervention_request:
    path:     /intervention/demande/{id}
    defaults:
        _controller: InterventionBundle:Intervention:demande
    requirements:
        id:  \d+

intervention_request_anonyme:
    path:     /intervention/demande
    defaults:
        _controller: InterventionBundle:Intervention:demandeAnonyme

intervention_list:
    path:   /intervention
    defaults:
        _controller: InterventionBundle:Intervention:liste

intervention_self:
    path: /intervention/maliste
    defaults: {_controller: InterventionBundle:Intervention:maListe}

demandes_recentes:
    path: /intervention/demandes_recentes
    defaults: {_controller: InterventionBundle:Intervention:recentDemandesListe}

intervention_view:
    path: /intervention/{id}
    defaults: {_controller: InterventionBundle:Intervention:consultation}
    requirements:
        id: \d+

demande_view:
    path: /intervention/{id}/demande
    defaults: {_controller: InterventionBundle:Intervention:consultationDemande}
    requirements:
        id: \d+

intervention_edit:
    path: /intervention/edit/{id}
    defaults: {_controller: InterventionBundle:Intervention:edit}
    requirements:
        id: \d+

intervention_self_attribute:
    path: /intervention/attribution
    defaults: {_controller: InterventionBundle:Intervention:attribution}

intervention_self_desattribute:
    path: /intervention/desattribution
    defaults: {_controller: InterventionBundle:Intervention:desattribution}

intervention_done:
    path: /intervention/realisation
    defaults: {_controller: InterventionBundle:Intervention:realisation}

intervention_multiple_done:
    path: /intervention/multiple/realisation
    defaults: {_controller: InterventionBundle:Intervention:realisationInterventions}

intervention_cancel:
    path: /intervention/annuler/{id}
    defaults: {_controller: InterventionBundle:Intervention:annuler}

# Route etablissement
etablissement_list:
    path:   /etablissement
    defaults:
        _controller: InterventionBundle:Etablissement:liste

etablissement_view:
    path:   /etablissement/{id}
    defaults:
        _controller: InterventionBundle:Etablissement:consultation
    requirements:
        id: \d+

etablissement_autocomplete:
    path : /etablissement/autocomplete
    defaults:
         _controller: InterventionBundle:Etablissement:etablissementAutocomplete

etablissement_verify_nom:
    path : /etablissement/verify
    defaults:
        _controller: InterventionBundle:Etablissement:verifyEtablissement

# Route Vente
vente_list:
    path:   /ventes
    defaults:
        _controller: InterventionBundle:Vente:liste

vente_view:
    path: /vente/{id}
    defaults: {_controller: InterventionBundle:Vente:consultation}
    requirements:
        id: \d+

vente_add:
    path: /vente/ajouter
    defaults: {_controller: InterventionBundle:Vente:add}

