intervention_request:
    path:     /intervention/demande
    defaults:
        _controller: InterventionBundle:Intervention:demande

intervention_list:
    path:   /intervention
    defaults:
        _controller: InterventionBundle:Intervention:liste
#        typeI: ""
#    requirements:
#        typeI: "plaidoyer|frimousse|autreIntervention"

intervention_attributed:
    path: /intervention/attribuees
    defaults: {_controller: InterventionBundle:Intervention:attribuees}

intervention_view:
    path: /intervention/{id}
    defaults: {_controller: InterventionBundle:Intervention:consultation}
    requirements:
        id: \d+

intervention_cancel:
    path: /intervention/annuler/{id}
    defaults: {_controller: InterventionBundle:Intervention:annuler}

etablissement_list:
    path:   /etablissement/{typeE}
    defaults:
        _controller: InterventionBundle:Etablissement:liste
        typeE: ""
    requirements:
        typeE: "enseignement|centre|autreEtablissement"

etablissement_view:
    path:   /etablissement/{id}
    defaults:
        _controller: InterventionBundle:Etablissement:consultation
    requirements:
        id: \d+
