# version 1.00 date 13/05/2016 auteur(s) Michel Cressant, Julie Pain

# Route intervention
intervention_admin_add:
    path:     /intervention/ajouter
    defaults: { _controller: InterventionBundle:Intervention:add }

intervention_admin_deletes:
    path:   /intervention/supprimer
    defaults: { _controller: InterventionBundle:Intervention:deleteInterventions }


intervention_attribute:
    path: /intervention/attributionA
    defaults: {_controller: InterventionBundle:Intervention:attributionABenevole}

intervention_desattribute:
    path: /intervention/desattributionA
    defaults: {_controller: InterventionBundle:Intervention:desattributionA}

# Route etablissement
etablissement_admin_add:
    path:     /etablissement/ajouter
    defaults: { _controller: InterventionBundle:Etablissement:add }

intervention_admin_delete:
    path:   /intervention/supprimer/{id}
    defaults: { _controller: InterventionBundle:Intervention:supprimer }
    requirements:
        id: \d+

etablissement_admin_delete:
    path:   /etablissement/supprimer/{id}
    defaults: { _controller: InterventionBundle:Etablissement:deleteEtablissement }
    requirements:
        id: \d+

etablissement_admin_deletes:
    path:   /etablissement/supprimer
    defaults: { _controller: InterventionBundle:Etablissement:deleteEtablissements }

etablissement_admin_edit:
    path:   /etablissement/edit/{id}
    defaults: { _controller: InterventionBundle:Etablissement:edit }

vente_admin_edit:
    path: /vente/edit/{id}
    defaults: {_controller: InterventionBundle:Vente:edit}
    requirements:
        id: \d+

vente_admin_delete:
    path: /vente/supprimer/{id}
    defaults: {_controller: InterventionBundle:Vente:deleteVente}
    requirements:
        id: \d+
