INSERT INTO niveau_theme (niveau, theme) VALUES ('petite section', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('petite section', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('petite section', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('petite section', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('petite section', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('petite-moyenne section', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('petite-moyenne section', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('petite-moyenne section', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('petite-moyenne section', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('petite-moyenne section', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('moyenne section', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('moyenne section', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('moyenne section', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('moyenne section', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('moyenne section', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('moyenne-grande section', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('moyenne-grande section', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('moyenne-grande section', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('moyenne-grande section', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('moyenne-grande section', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('grande section', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('grande section', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('grande section', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('grande section', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('grande section', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('petite-moyenne-grande section', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('petite-moyenne-grande section', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('petite-moyenne-grande section', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('petite-moyenne-grande section', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('petite-moyenne-grande section', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CP', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CP', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CP', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CP', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CP', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CP-CE1', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CP-CE1', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CP-CE1', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CP-CE1', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CP-CE1', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE1', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE1', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE1', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE1', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE1', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE1-CE2', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE1-CE2', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE1-CE2', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE1-CE2', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE1-CE2', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE2', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE2', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE2', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE2', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE2', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE2-CM1', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE2-CM1', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE2-CM1', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE2-CM1', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE2-CM1', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CM1', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CM1', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CM1', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CM1', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CM1', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CM1-CM2', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CM1-CM2', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CM1-CM2', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CM1-CM2', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CM1-CM2', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CM2', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CM2', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CM2', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CM2', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CM2', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('6eme', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('6eme', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('6eme', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('6eme', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('6eme', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('5eme', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('5eme', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('5eme', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('5eme', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('5eme', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('4eme', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('4eme', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('4eme', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('4eme', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('4eme', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('3eme', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('3eme', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('3eme', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('3eme', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('3eme', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('2nde', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('2nde', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('2nde', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('2nde', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('2nde', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('1ere', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('1ere', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('1ere', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('1ere', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('1ere', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('terminale', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('terminale', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('terminale', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('terminale', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('terminale', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L1', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L1', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L1', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L1', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L1', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L2', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L2', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L2', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L2', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L2', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L3', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L3', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L3', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L3', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L3', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M1', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M1', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M1', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M1', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M1', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M2', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M2', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M2', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M2', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M2', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('autre', 'convention internationale des droits de l enfant');
INSERT INTO niveau_theme (niveau, theme) VALUES ('autre', 'education');
INSERT INTO niveau_theme (niveau, theme) VALUES ('autre', 'sante et alimentation');
INSERT INTO niveau_theme (niveau, theme) VALUES ('autre', 'eau');
INSERT INTO niveau_theme (niveau, theme) VALUES ('autre', 'harcelement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CP', 'sante en generale');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CP', 'travail des enfants');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CP-CE1', 'sante en generale');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CP-CE1', 'travail des enfants');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE1', 'sante en generale');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE1', 'travail des enfants');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE1-CE2', 'sante en generale');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE1-CE2', 'travail des enfants');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE2', 'sante en generale');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE2', 'travail des enfants');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE2-CM1', 'sante en generale');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CE2-CM1', 'travail des enfants');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CM1', 'sante en generale');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CM1', 'travail des enfants');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CM1-CM2', 'sante en generale');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CM1-CM2', 'travail des enfants');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CM2', 'sante en generale');
INSERT INTO niveau_theme (niveau, theme) VALUES ('CM2', 'travail des enfants');
INSERT INTO niveau_theme (niveau, theme) VALUES ('6eme', 'sante en generale');
INSERT INTO niveau_theme (niveau, theme) VALUES ('6eme', 'travail des enfants');
INSERT INTO niveau_theme (niveau, theme) VALUES ('5eme', 'sante en generale');
INSERT INTO niveau_theme (niveau, theme) VALUES ('5eme', 'travail des enfants');
INSERT INTO niveau_theme (niveau, theme) VALUES ('4eme', 'sante en generale');
INSERT INTO niveau_theme (niveau, theme) VALUES ('4eme', 'travail des enfants');
INSERT INTO niveau_theme (niveau, theme) VALUES ('3eme', 'sante en generale');
INSERT INTO niveau_theme (niveau, theme) VALUES ('3eme', 'travail des enfants');
INSERT INTO niveau_theme (niveau, theme) VALUES ('2nde', 'sante en generale');
INSERT INTO niveau_theme (niveau, theme) VALUES ('2nde', 'travail des enfants');
INSERT INTO niveau_theme (niveau, theme) VALUES ('1ere', 'sante en generale');
INSERT INTO niveau_theme (niveau, theme) VALUES ('1ere', 'travail des enfants');
INSERT INTO niveau_theme (niveau, theme) VALUES ('terminale', 'sante en generale');
INSERT INTO niveau_theme (niveau, theme) VALUES ('terminale', 'travail des enfants');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L1', 'sante en generale');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L1', 'travail des enfants');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L2', 'sante en generale');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L2', 'travail des enfants');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L3', 'sante en generale');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L3', 'travail des enfants');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M1', 'sante en generale');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M1', 'travail des enfants');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M2', 'sante en generale');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M2', 'travail des enfants');
INSERT INTO niveau_theme (niveau, theme) VALUES ('autre', 'sante en generale');
INSERT INTO niveau_theme (niveau, theme) VALUES ('autre', 'travail des enfants');
INSERT INTO niveau_theme (niveau, theme) VALUES ('6eme', 'urgences mondiales');
INSERT INTO niveau_theme (niveau, theme) VALUES ('6eme', 'enfants et soldats');
INSERT INTO niveau_theme (niveau, theme) VALUES ('5eme', 'urgences mondiales');
INSERT INTO niveau_theme (niveau, theme) VALUES ('5eme', 'enfants et soldats');
INSERT INTO niveau_theme (niveau, theme) VALUES ('4eme', 'urgences mondiales');
INSERT INTO niveau_theme (niveau, theme) VALUES ('4eme', 'enfants et soldats');
INSERT INTO niveau_theme (niveau, theme) VALUES ('3eme', 'urgences mondiales');
INSERT INTO niveau_theme (niveau, theme) VALUES ('3eme', 'enfants et soldats');
INSERT INTO niveau_theme (niveau, theme) VALUES ('2nde', 'urgences mondiales');
INSERT INTO niveau_theme (niveau, theme) VALUES ('2nde', 'enfants et soldats');
INSERT INTO niveau_theme (niveau, theme) VALUES ('1ere', 'urgences mondiales');
INSERT INTO niveau_theme (niveau, theme) VALUES ('1ere', 'enfants et soldats');
INSERT INTO niveau_theme (niveau, theme) VALUES ('terminale', 'urgences mondiales');
INSERT INTO niveau_theme (niveau, theme) VALUES ('terminale', 'enfants et soldats');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L1', 'urgences mondiales');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L1', 'enfants et soldats');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L2', 'urgences mondiales');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L2', 'enfants et soldats');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L3', 'urgences mondiales');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L3', 'enfants et soldats');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M1', 'urgences mondiales');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M1', 'enfants et soldats');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M2', 'urgences mondiales');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M2', 'enfants et soldats');
INSERT INTO niveau_theme (niveau, theme) VALUES ('autre', 'urgences mondiales');
INSERT INTO niveau_theme (niveau, theme) VALUES ('autre', 'enfants et soldats');
INSERT INTO niveau_theme (niveau, theme) VALUES ('2nde', 'VIH et sida');
INSERT INTO niveau_theme (niveau, theme) VALUES ('2nde', 'role de l Unicef');
INSERT INTO niveau_theme (niveau, theme) VALUES ('2nde', 'millenaire pour le developpement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('1ere', 'VIH et sida');
INSERT INTO niveau_theme (niveau, theme) VALUES ('1ere', 'role de l Unicef');
INSERT INTO niveau_theme (niveau, theme) VALUES ('1ere', 'millenaire pour le developpement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('terminale', 'VIH et sida');
INSERT INTO niveau_theme (niveau, theme) VALUES ('terminale', 'role de l Unicef');
INSERT INTO niveau_theme (niveau, theme) VALUES ('terminale', 'millenaire pour le developpement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L1', 'VIH et sida');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L1', 'role de l Unicef');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L1', 'millenaire pour le developpement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L2', 'VIH et sida');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L2', 'role de l Unicef');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L2', 'millenaire pour le developpement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L3', 'VIH et sida');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L3', 'role de l Unicef');
INSERT INTO niveau_theme (niveau, theme) VALUES ('L3', 'millenaire pour le developpement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M1', 'VIH et sida');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M1', 'role de l Unicef');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M1', 'millenaire pour le developpement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M2', 'VIH et sida');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M2', 'role de l Unicef');
INSERT INTO niveau_theme (niveau, theme) VALUES ('M2', 'millenaire pour le developpement');
INSERT INTO niveau_theme (niveau, theme) VALUES ('autre', 'VIH et sida');
INSERT INTO niveau_theme (niveau, theme) VALUES ('autre', 'role de l Unicef');
INSERT INTO niveau_theme (niveau, theme) VALUES ('autre', 'millenaire pour le developpement');
