# version 1.00, date 04/03/16, auteur Pierre Porche
# Compilation
all: sp

sp:
	make -C SP


# Archivage
archive: archivesp

archivesp:
	make -C SP archive



# Nettoyage
clean: cleansp

cleansp:
	make -C SP clean

