postgresql_users:
  - name: unipik
    pass: $2a$08$kvwZ8BRMT7E5AniFlPDbqe7bpLUHJyQoPdpu1/zUVujw5C3QWX4MO
    encrypted: yes


database_password: 7mnGOBDwr2tZsEdgksUTKrl0W9Kwr45TSy9G3hWTdGv9
secret: RQJUhBeZBM2sfWc6X3Sub9Rwq9mjmBO4pXcoxfecw9yYGI85olxm3QWyfYi6psvn7q5l1c3ASv1ZW5DoMoLgObSiT9IWXNYH
mailer_password: taistoijulie
second_mailer_password: biscotte
