# version 1.00, date 20/02/16, auteur Michel Cressant
# Compilation
all: bd

bd:
	make -C BD

# Archivage
archive: archivebd

archivebd:
	make -C BD archive

# Nettoyage
clean: cleanbd

cleanbd:
	make -C BD clean
