# version 1.01 date 30/03/2016 auteur(s) Michel Cressant
# version 1.00 date 24/02/2016 auteur(s) Pierre Porche, Michel Cressant

# Compilation
all: GenDoc

GenDoc:
	./genDoc.sh


# Nettoyage
clean: cleanDoc

cleanDoc:
	rm -r ./out/*/
	rm ./out/index.html
	rm ./out/.htaccess
