# version 1.00, date 24/02/16, auteur Pierre Porche
# Compilation
all: dcp

dcp:
	make -C DCP



# Archivage
archive: archivedcp

archivedcp:
	make -C DCP archive



# Nettoyage
clean: cleandcp

cleanlot1:
	make -C DCP clean

