# Compilation
all: modeleea

modeleea:
	make -C modeleEA

# Archivage
archive: archivemodeleea

archivemodeleea:
	make -C modeleEA archive

# Nettoyage
clean: cleanmodeleea

cleanmodeleea:
	make -C modeleEA clean
