# version 1.00 date 13/05/2016 auteur(s) Michel Cressant, Julie Pain
Unipik\ArchitectureBundle\Entity\Adresse:
    type: entity
    table: adresse
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        ville:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        adresse:
            type: string
            nullable: false
            length: 500
            options:
                fixed: false
        complement:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        geolocalisation:
            type: geography
            nullable: true
            options:
                fixed: false
                geography_type: POINT
                srid: 4326
    lifecycleCallbacks: {  }
