# version 1.00 date 13/05/2016 auteur(s) Michel Cressant, Julie Pain
Unipik\ArchitectureBundle\Entity\Adresse:
    type: entity
    table: adresse
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        adresse:
            type: string
            nullable: false
            length: 500
            options:
                fixed: false
        complement:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        geolocalisation:
            type: geography
            nullable: true
            options:
                fixed: false
                geography_type: POINT
                srid: 4326
    manyToOne:
        ville:
            targetEntity: Ville
            cascade: { }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ville_id:
                    referencedColumnName: id
            orphanRemoval: false
        codePostal:
            targetEntity: CodePostal
            cascade: { }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                code_postal_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
