architecture_homepage:
    path:     /accueil
    defaults:
        _controller: ArchitectureBundle:Volunteer:index

architecture_add:
  path: /ajouter
  defaults:
      _controller: ArchitectureBundle:Volunteer:add