architecture_homepage:
    path:     /
    defaults: { _controller: ArchitectureBundle:Architecture:index }

architecture_school_add:
    path:     /demande
    defaults:
        _controller: ArchitectureBundle:Architecture:demandeIntervention

architecture_test:
    path:     /test/{id}
    defaults: { _controller: ArchitectureBundle:Architecture:test }

logout:
    path:   /logout
    defaults: { _controller: ArchitectureBundle:Architecture:logout}
