architecture_homepage:
    path:     /
    defaults: { _controller: ArchitectureBundle:Architecture:index }

architecture_noJavascript:
    path:     /erreurJS
    defaults: { _controller: ArchitectureBundle:Architecture:noJS }

architecture_departement_autocomplete:
    path: /departement/autocomplete
    defaults:
        _controller: ArchitectureBundle:Architecture:autocompleteDepartement

architecture_verify_departement:
    path: /departement/verify
    defaults:
        _controller: ArchitectureBundle:Architecture:verifyDepartement

architecture_verify_ville:
    path: /ville/verify
    defaults:
        _controller: ArchitectureBundle:Architecture:verifyVille

architecture_ville_autocomplete:
    path: /ville/autocomplete
    defaults:
        _controller: ArchitectureBundle:Architecture:autocompleteVille

architecture_code_autocomplete:
    path: /codePostal/autocomplete
    defaults:
        _controller: ArchitectureBundle:Architecture:autocompleteCode

architecture_code_postal:
    path: /codepostal
    defaults:
        _controller: ArchitectureBundle:Architecture:codePostal

architecture_ville:
    path: /ville
    defaults:
        _controller: ArchitectureBundle:Architecture:ville
