architecture_homepage:
    path:     /
    defaults: { _controller: ArchitectureBundle:Architecture:index }

architecture_noJavascript:
    path:     /erreurJS
    defaults: { _controller: ArchitectureBundle:Architecture:noJS }