architecture_homepage:
    path:     /
    defaults: { _controller: ArchitectureBundle:Architecture:index }

architecture_school_add:
    path:     /demande
    defaults:
        _controller: ArchitectureBundle:Architecture:demandeIntervention

architecture_profile:
    path:     /profil/{id}
    defaults: { _controller: ArchitectureBundle:Architecture:profile }
    requirements:
            id: \d+

logout:
    path:   /logout
    defaults: { _controller: ArchitectureBundle:Architecture:logout}
