#Routes générales pour l'accueil.
architecture_root:
    path: /
    defaults:
        _controller: ArchitectureBundle:Home:index

architecture_homepage:
    path: /accueil
    defaults:
        _controller: ArchitectureBundle:Home:index

#Routes pour les hello worlds
architecture_hello_simple:
    path: /hello
    defaults:
        _controller: ArchitectureBundle:Hello:helloUnicef

architecture_hello_complex:
    path: /hello/name
    defaults:
        _controller: ArchitectureBundle:Hello:helloName

#Routes pour les bénévoles.
architecture_volunteer_homepage:
    path:     /benevole/accueil
    defaults:
        _controller: ArchitectureBundle:Volunteer:index

architecture_volunteer_add:
    path: /benevole/ajouter
    defaults:
        _controller: ArchitectureBundle:Volunteer:add

architecture_volunteer_view:
    path: /benevole/details/{id}
    defaults:
        _controller: ArchitectureBundle:Volunteer:view

architecture_volunteer_delete:
    path: /benevole/supprimer/{id}
    defaults:
        _controller: ArchitectureBundle:Volunteer:delete

#Routes pour les établissements.
architecture_school_root:
    path:     /etablissement/
    defaults:
        _controller: ArchitectureBundle:School:index

architecture_school_add:
    path:     /etablissement/ajouter
    defaults:
        _controller: ArchitectureBundle:School:add

architecture_school_homepage:
    path:     /etablissement/accueil
    defaults:
        _controller: ArchitectureBundle:School:index

architecture_school_view:
    path: /etablissement/details/{id}
    defaults:
        _controller: ArchitectureBundle:School:view

architecture_school_delete:
    path: /etablissement/supprimer/{id}
    defaults:
        _controller: ArchitectureBundle:School:delete

#Routes pour les interventions.
architecture_intervention_homepage:
    path:     /intervention/accueil
    defaults:
        _controller: ArchitectureBundle:Intervention:index

architecture_intervention_add:
    path: /intervention/ajouter
    defaults:
        _controller: ArchitectureBundle:Intervention:add

architecture_intervention_view:
    path: /intervention/details/{id}
    defaults:
        _controller: ArchitectureBundle:Intervention:view

architecture_intervention_delete:
    path: /intervention/supprimer/{id}
    defaults:
        _controller: ArchitectureBundle:Intervention:delete
