architecture_volunteer_root:
  path: /
  defaults:
      _controller: ArchitectureBundle:Volunteer:index

architecture_volunteer_homepage:
    path:     /benevole/accueil
    defaults:
        _controller: ArchitectureBundle:Volunteer:index

architecture_volunteer_add:
  path: /benevole/ajouter
  defaults:
      _controller: ArchitectureBundle:Volunteer:add

architecture_volunteer_view:
  path: /benevole/details/{id}
  defaults:
      _controller: ArchitectureBundle:Volunteer:view

architecture_volunteer_delete:
  path: /benevole/supprimer/{id}
  defaults:
      _controller: ArchitectureBundle:Volunteer:delete
