#chemin générale pour l'accueil
architecture_root:
    path: /
    defaults:
        _controller: ArchitectureBundle:Home:index

architecture_homepage:
    path: /accueil
    defaults:
        _controller: ArchitectureBundle:Home:index

#chemin pour les volontaires
architecture_volunteer_homepage:
    path:     /benevole/accueil
    defaults:
        _controller: ArchitectureBundle:Volunteer:index

architecture_volunteer_add:
    path: /benevole/ajouter
    defaults:
        _controller: ArchitectureBundle:Volunteer:add

architecture_volunteer_view:
    path: /benevole/details/{id}
    defaults:
        _controller: ArchitectureBundle:Volunteer:view

architecture_volunteer_delete:
    path: /benevole/supprimer/{id}
    defaults:
        _controller: ArchitectureBundle:Volunteer:delete

#chemin pour les écoles
architecture_school_root:
    path:     /etablissement/
    defaults:
        _controller: ArchitectureBundle:School:index

architecture_school_homepage:
    path:     /etablissement/accueil
    defaults:
        _controller: ArchitectureBundle:School:index

