services:
    app.form.adresse.adresse:
        class: Unipik\ArchitectureBundle\Form\Adresse\AdresseType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.mailing:
            class: Unipik\MailBundle\Form\MailingType
            arguments: ["@doctrine.orm.entity_manager"]
            tags:
                - { name: form.type }