# version 1.00 date 13/05/2016 auteur(s) Michel Cressant, Julie Pain
NiveauTheme:
    type: entity
    table: niveau_theme
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        niveau:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        theme:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
    manyToMany:
        comite:
            targetEntity: Unipik\UserBundle\Entity\Comite
            cascade: {  }
            fetch: LAZY
            mappedBy: niveauTheme
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
