# version 1.00 date 13/05/2016 auteur(s) Michel Cressant, Julie Pain
Region:
    type: entity
    table: region
    indexes:
        IDX_F62F176A6E44244:
            columns:
                - pays_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nom:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    manyToOne:
        pays:
            targetEntity: Pays
            cascade: [ "persist" ]
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                pays_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
