Unipik\MailBundle\Entity\MailHistorique:
    type: entity
    repositoryClass: Unipik\MailBundle\Entity\MailHistoriqueRepository
    table: mail_historique
    indexes:
        IDX_D11814ABFF631228:
            columns:
            - id_etablissement
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        date_envoi:
            type: datetime
            nullable: true
        type_email:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        etablissement:
            targetEntity: Unipik\InterventionBundle\Entity\Etablissement
            cascade: ["persist"]
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_etablissement:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
