ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/ubuntu1604"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.name = "integ"
    v.memory = 512
    v.cpus = 2
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.hostname = "integ"
  config.vm.network :private_network, ip: "192.168.33.77"
  config.vm.network :public_network, bridge: "HostInterfaceNetworking-eth1", :mac =>  "080027f45751"

  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define :integ do |j|
  end

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    ansible.inventory_path = "provisioning/inventory"
    ansible.sudo = true
    #ansible.verbose = "vvvv"
  end

end
