# version 1.00, date 04/03/16, auteur Pierre Porche
# Compilation
all: revuesUn

revuesUn:
	make -C revue1


# Archivage
archive: archiverevueUn

archiverevueUn:
	make -C revue1 archive



# Nettoyage
clean: cleanrevueUn

cleanrevueUn:
	make -C revue1 clean

