# version 1.00 date 04/03/2016 auteur(s) Pierre Porche

# Compilation
all: revueUn revueDeux revueTrois

revueUn:
	make -C revue1

revueDeux:
	make -C revue2

revueTrois:
	make -C revue3




# Archivage
archive: archiverevueUn archiverevueDeux archiverevueTrois

archiverevueUn:
	make -C revue1 archive

archiverevueDeux:
	make -C revue2 archive

archiverevueTrois:
	make -C revue3 archive





# Nettoyage
clean: cleanrevueUn cleanrevueDeux cleanrevueTrois

cleanrevueUn:
	make -C revue1 clean

cleanrevueDeux:
	make -C revue2 clean

cleanrevueDeux:
	make -C revue3 clean

