# version 1.00, date 20/02/16, auteur Sergi Colomies
# Compilation
all: pvfps

pvfps:
	make -C PVFPS

# Archivage
archive: archivepvfps 

archivepvfps:
	make -C PVFPS archive

# Nettoyage
clean: cleanpvfps 

cleanpvfps:
	make -C PVFPS clean
