# version 1.00, date 24/02/16, auteur Pierre Porche
# Compilation
all: modeleea

modeleea:
	make -C modeleEA



# Archivage
archive: archivemodeleea

archivemodeleea:
	make -C modeleEA archive



# Nettoyage
clean: cleanmodeleea

cleanlot1:
	make -C modeleEA clean

