# version 1.00 date 30/03/2016 auteur(s) Sergi Colomies

# Compilation
all: pvr

pvr:
	make -C PVR

# Archivage
archive: archivepvr 

archivepvr:
	make -C PVR archive

# Nettoyage
clean: cleanpvr 

cleanpvr:
	make -C PVR clean
