fos_user_registration_confirm:
    path: /confirmer/{token}
    defaults:
        _controller: FOSUserBundle:Registration:confirm

fos_user_registration_confirmed:
    path: /confirmed
    defaults:
        _controller: UserBundle:Registration:confirmed

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_security_check:
    path: /login_check
    defaults:
        _controller: FOSUserBundle:Security:check

user_security_logout:
    path: /logout
    defaults:
        _controller: FOSUserBundle:Security:logout

user_security_login:
    path: /login
    defaults:
        _controller: UserBundle:Security:loginPage

user_profile_show:
    path: /profil
    defaults:
        _controller: FOSUserBundle:Profile:show

user_profile_edit:
    path: /profil/edit
    defaults:
        _controller: UserBundle:Profile:edit

user_change_password:
    path: /change-password
    defaults:
        _controller: FOSUserBundle:ChangePassword:changePassword


