user_admin_list:
    path: /benevoles
    defaults:
        _controller: UserBundle:User:liste

user_admin_register:
    path: /register
    defaults:
        _controller: UserBundle:Registration:register

fos_user_registration_check_email:
    path: /verification-email
    defaults:
        _controller: FOSUserBundle:Registration:checkEmail

#user_admin_confirm:
#    path: /confirmer/{token}
#    defaults:
#        _controller: FOSUserBundle:Registration:confirm

#user_admin_confirmed:
#    path: /confirme
#    defaults:
#        _controller: FOSUserBundle:Registration:confirmed
