fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

fos_user_security_check:
    path: /login_check
    defaults:
        _controller: FOS\UserBundle:Security:check

fos_user_security_logout:
    path: /logout
    defaults:
        _controller: UserBundle:Security:logout

fos_user_security_login:
    path: /login
    defaults:
        _controller: UserBundle:Security:loginPage

fos_user_profile_show:
    path: /profil
    defaults:
        _controller: UserBundle:User:viewProfile

fos_user_profile_edit:
    path: /profil/edit
    defaults:
        _controller: UserBundle:User:editProfile

