user_admin_list:
    path: /benevoles
    defaults:
        _controller: UserBundle:User:liste

user_admin_register:
    path: /register
    defaults:
        _controller: UserBundle:Registration:register

fos_user_registration_check_email:
    path: /verification-email
    defaults:
        _controller: FOSUserBundle:Registration:checkEmail

user_admin_delete:
    path: /benevole/delete/{username}
    defaults:
        _controller: UserBundle:User:delete

user_admin_deletes:
    path: /benevole/deletes
    defaults:
        _controller: UserBundle:User:deletes

user_admin_profil_benevole:
    path: /benevole/profile/{username}
    defaults:
        _controller: UserBundle:User:showProfile