user_admin_list:
    path: /benevoles
    defaults:
        _controller: UserBundle:User:liste

fos_user_admin_register:
    path: /register
    defaults:
        _controller: UserBundle:Registration:register

user_admin_register_city_autocomplete:
    path: /ville/autocomplete
    defaults:
        _controller: UserBundle:Registration:autocomplete

fos_user_registration_check_email:
    path: /verification-email
    defaults:
        _controller: FOSUserBundle:Registration:checkEmail

user_admin_delete:
    path: /benevole/delete/{username}
    defaults:
        _controller: UserBundle:User:deleteVolunteer

user_admin_deletes:
    path: /benevole/deletes
    defaults:
        _controller: UserBundle:User:deleteVolunteers

user_admin_profil_benevole:
    path: /benevole/profile/{username}
    defaults:
        _controller: UserBundle:User:showProfile

user_admin_profil_edit:
    path: /benevole/profil/edit/{username}
    defaults:
          _controller: UserBundle:User:edit
