#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

fos_user_registration_confirm:
    path: /confirmer/{token}
    defaults:
        _controller: FOSUserBundle:Registration:confirm

fos_user_registration_confirmed:
    path: /confirme
    defaults:
        _controller: FOSUserBundle:Registration:confirmed

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_security_check:
    path: /login_check
    defaults:
        _controller: FOSUserBundle:Security:check

fos_user_security_logout:
    path: /logout
    defaults:
        _controller: FOSUserBundle:Security:logout

fos_user_security_login:
    path: /login
    defaults:
        _controller: UserBundle:Security:loginPage

fos_user_profile_show:
    path: /profil
    defaults:
        _controller: FOSUserBundle:Profile:show

fos_user_profile_edit:
    path: /profil/edit
    defaults:
        _controller: FOSUserBundle:Profile:edit

fos_user_change_password:
    path: /change-password
    defaults:
        _controller: FOSUserBundle:ChangePassword:changePassword

