services:
    unipik_user.listener.flash:
        class: Unipik\UserBundle\EventListener\FlashListener
        tags:
            - { name: kernel.event_subscriber }
        arguments: ['@session', '@translator']
    app.form.profile:
        class: Unipik\UserBundle\Form\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: user_profile }
    app.form.registration:
        class: Unipik\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: user_registration }



